In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Dropout, MaxPooling1D, Flatten, LSTM
from sklearn.model_selection import train_test_split
from keras import optimizers
from keras.models import load_model
from keras.callbacks import ModelCheckpoint
import pandas as pd
from keras.regularizers import l2
import keras
from keras.layers import LSTM, Dense,Input, Conv2D, Flatten, BatchNormalization

In [8]:
filename="DB_modified.csv"
dataset = pd.read_csv(filename)
dataset
# Q1 = dataset.quantile(0.25)
# Q3 = dataset.quantile(0.75)
# IQR = Q3 - Q1
# # print(IQR)
# # print(dataset.shape)
# dataset = dataset[~((dataset < (Q1 - 1.5 * IQR)) |(dataset > (Q3 + 1.5 * IQR))).any(axis=1)]
# print(dataset.shape)
dataset =np.array(dataset)[1:-1]
dataset=np.asfarray(dataset,float)
dataset.shape

(2158, 8)

In [9]:
X=dataset[:,:4]
print(X)
# X=(X-np.mean(X))/np.std(X)

# X=dataset[:,2]
X[:,0]=(X[:,0]-np.mean(X[:,0]))/np.std(X[:,0])
X[:,1]=(X[:,1]-np.mean(X[:,1]))/np.std(X[:,1])
X[:,2]=(X[:,2]-np.mean(X[:,2]))/np.std(X[:,2])
X[:,3]=(X[:,3]-np.mean(X[:,3]))/np.std(X[:,3])

# X[:,1]=X[:,1]/np.max(X[:,1])
y=dataset[:,4:7]
# Vthin=dataset[:,-2]
# np.concatenate((X, np.expand_dims(Vthin, 1)), 1)
# print(X)
print(y.shape)
# X=np.expand_dims(X, 1)
y,X

[[0.0e+00 2.0e+16 1.5e-02 1.7e-01]
 [0.0e+00 2.0e+16 1.5e-02 1.9e-01]
 [0.0e+00 2.0e+16 1.5e-02 2.1e-01]
 ...
 [1.0e+00 1.0e+19 2.9e-02 2.5e-01]
 [1.0e+00 1.0e+19 2.9e-02 2.7e-01]
 [1.0e+00 1.0e+19 2.9e-02 2.9e-01]]
(2158, 3)


(array([[ 38.9934 ,  82.224  ,  -0.716  ],
        [ 58.829  ,  90.156  ,  -0.977  ],
        [ 82.97375,  97.828  ,  -1.239  ],
        ...,
        [404.002  , 101.472  ,  -5.41   ],
        [444.592  , 106.572  ,  -5.935  ],
        [483.73   , 111.408  ,  -6.464  ]]),
 array([[-1.        , -0.69961252, -1.5284699 , -1.16264952],
        [-1.        , -0.69961252, -1.5284699 , -0.77509968],
        [-1.        , -0.69961252, -1.5284699 , -0.38754984],
        ...,
        [ 1.        ,  2.47781879,  1.5284699 ,  0.38754984],
        [ 1.        ,  2.47781879,  1.5284699 ,  0.77509968],
        [ 1.        ,  2.47781879,  1.5284699 ,  1.16264952]]))

In [10]:
dfgan = pd.read_csv("fromGANwo-ve.csv")
# Q1 = dfgan.quantile(0.25)
# Q3 = dfgan.quantile(0.75)
# IQR = Q3 - Q1
# print(IQR)
# print(dfgan.shape)
# dfgan = dfgan[~((dfgan < (Q1 - 1.5 * IQR)) |(dfgan > (Q3 + 1.5 * IQR))).any(axis=1)]
# print(dfgan.shape)
dfgan =np.array(dfgan)

dfgan=np.asfarray(dfgan,float)
xGAN=dfgan[:,0:4]
print(xGAN)
xGAN[:,0]=(xGAN[:,0]-np.mean(xGAN[:,0]))/np.std(xGAN[:,0])
xGAN[:,1]=(xGAN[:,1]-np.mean(xGAN[:,1]))/np.std(xGAN[:,1])
xGAN[:,2]=(xGAN[:,2]-np.mean(xGAN[:,2]))/np.std(xGAN[:,2])
xGAN[:,3]=(xGAN[:,3]-np.mean(xGAN[:,3]))/np.std(xGAN[:,3])
yGAN=dfgan[:,4:7]
print(xGAN)

[[-0.6972414   1.4884295   0.51256835  0.5147029 ]
 [-1.0893219   1.1557536  -0.9450898   1.4321591 ]
 [ 0.9408671  -0.574       0.32613173  0.571942  ]
 ...
 [ 0.86686724 -0.25266343  0.79319525  1.412123  ]
 [-0.9377408  -0.06915441 -1.0210751  -1.4790384 ]
 [-0.735737    1.30408     0.27639705 -1.70117   ]]
[[-0.85502875  1.10179663  0.58732684  0.50957876]
 [-1.29633887  0.79686945 -0.91004294  1.46655927]
 [ 0.98876059 -0.78860423  0.39581105  0.56928374]
 ...
 [ 0.90546931 -0.49407056  0.87559899  1.44566001]
 [-1.12572525 -0.32586815 -0.98809834 -1.57005355]
 [-0.89835786  0.93282385  0.34472142 -1.80175465]]


In [11]:
xtotal=np.vstack((X, xGAN))
ytotal=np.vstack((y, yGAN))
print(xtotal)
ytotal.shape

[[-1.         -0.69961252 -1.5284699  -1.16264952]
 [-1.         -0.69961252 -1.5284699  -0.77509968]
 [-1.         -0.69961252 -1.5284699  -0.38754984]
 ...
 [ 0.90546931 -0.49407056  0.87559899  1.44566001]
 [-1.12572525 -0.32586815 -0.98809834 -1.57005355]
 [-0.89835786  0.93282385  0.34472142 -1.80175465]]


(3111, 3)

In [12]:
x_train, x_test, y_train, y_test = train_test_split(xtotal, ytotal, test_size=0.15, random_state=42, shuffle=True)
print(x_train.shape)
x_train, x_cv, y_train, y_cv = train_test_split(x_train, y_train, test_size=0.15, random_state=42, shuffle=True)
print(y_train.shape)

(2644, 4)
(2247, 3)


In [13]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(x_cv.shape)
print(y_cv.shape)

(2247, 4)
(2247, 3)
(467, 4)
(467, 3)
(397, 4)
(397, 3)


In [14]:
# #SVR
# from sklearn.svm import SVR
# regressor = SVR(kernel='poly', degree=20)
# regressor.fit(x_train,y_train)
# for i in range(50):
#     y_pred = regressor.predict([x_test[i]])
#     print(y_pred-y_test[i])

In [18]:
x_traindim =np.expand_dims(x_train, 1)
y_traindim =np.expand_dims(y_train, 1)
x_cvdim =np.expand_dims(x_cv, 1)
y_cvdim =np.expand_dims(y_cv, 1)
x_testdim =np.expand_dims(x_test, 1)
y_testdim =np.expand_dims(y_test, 1)
print(x_traindim)
print(x_traindim.shape)

[[[ 1.03335528  1.77847337 -0.30606683 -1.10101673]]

 [[ 0.86371599 -0.36184192 -0.95099599 -0.29728895]]

 [[-1.         -0.69961252 -1.5284699  -0.77509968]]

 ...

 [[-1.         -0.06922033 -0.65505853 -1.55019935]]

 [[-1.         -0.4512762   0.65505853  1.55019935]]

 [[ 1.         -0.67414212 -0.65505853  0.77509968]]]
(2247, 1, 4)


In [26]:
for m in range(3):
    for k in range(3):
        for i in range(3):
                c1=32*2**m
                c2=32*2**k
                c3=32*2**i
#                 cnt=cnt+1
                if(not((c1==32 and c2==32 and c3==32)or (c1==32 and c2==32 and c3==64)or(c1==32 and c2==64 and c3==32)or(c1==64 and c2==32 and c3==32)or (c1==32 and c2==32 and c3==128))):
                    filename='L'+str(c1)+'L'+str(c2)+'L'+str(c3)
                    
                    modelfilepath="E:\\Simulations\\Silvaco\\\\2D HEMT\\EDL\\DATA for modeling\\modelLSTMvar_2D64_D3\\"+filename
                    
                    model = Sequential()
                    model.add(LSTM(c1, return_sequences=True, input_shape=(x_traindim[1].shape)))
                    model.add(LSTM(c2, return_sequences=True))
                    model.add(LSTM(c3, return_sequences=False))
                    # model.add(LSTM(16, return_sequences=True))
                    # model.add(LSTM(16, return_sequences=True))
                    # model.add(LSTM(16, return_sequences=True))
                    # model.add(LSTM(32, return_sequences=True))
                    # model.add(LSTM(16))

                    model.add(Dense(64, activation='relu'))
                    model.add(Dense(64, activation='relu'))

                    # model.add(Dense(64, activation='relu'))
                    # # # model.add(BatchNormalization())
                    # model.add(Dense(128, activation='relu'))
                    # model.add(Dense(64, activation='relu'))
                    # model.add(Dense(64, activation='relu'))
                    # model.add(Dense(64, activation='relu'))
                    # model.add(BatchNormalization())
                    # model.add(Dense(64, activation='relu'))
                    # model.add(Dense(128, activation='relu'))
                    # model.add(Dense(512, activation='relu'))
                    # model.add(Dense(128, activation='relu'))
                    # model.add(Dense(64, activation='relu'))
                    # model.add(Dense(128, activation='relu'))
                    # model.add(Dense(64, activation='relu'))
                    # model.add(Dense(64, activation='relu'))
                    # model.add(Dropout(0.5))
                    # model.add(Dense(64, activation='relu'))
                    # model.add(Dense(64, activation='relu'))
                    model.add(Dense(3, activation='linear'))
#                     opt=keras.optimizers.adam(0.001)
                    model.compile(loss='mean_squared_error', optimizer="adam", metrics=['MSE'])
                    model.summary()
                    filepath="E:\\Simulations\\Silvaco\\\\2D HEMT\\EDL\\DATA for modeling\\modelLSTMvar_2D64_D3\\latestmodel.hdf5"
                    checkpointer = ModelCheckpoint( monitor='val_loss',filepath=filepath, verbose=1, save_best_only=True)
                    history3=model.fit(x_traindim,y_train, validation_data=(x_cvdim, y_cv), epochs=1500, batch_size=16, callbacks=[checkpointer])
                    minloss=round(min(history3.history['val_loss']), 1) 
                    modelfilepath="E:\\Simulations\\Silvaco\\\\2D HEMT\\EDL\\DATA for modeling\\modelLSTMvar_2D64_D3\\"+filename+'_'+str(minloss)
                    df=pd.DataFrame(history3.history)
                    model.save(modelfilepath+'.h5')
                    df.to_csv(modelfilepath+'.csv')
                    


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 1, 32)             4736      
_________________________________________________________________
lstm_4 (LSTM)                (None, 1, 64)             24832     
_________________________________________________________________
lstm_5 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dense_15 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_16 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_17 (Dense)             (None, 3)                 195       
Total params: 71,107
Trainable params: 71,107
Non-trainable params: 0
__________________________________________________

KeyboardInterrupt: 

In [37]:
#model used for only actualdatabut now being testd for GAN too
model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(x_train[1].shape)))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(3, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['MSE'])
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_30 (Dense)             (None, 32)                160       
_________________________________________________________________
dense_31 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_32 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_33 (Dense)             (None, 64)                2112      
_________________________________________________________________
dense_34 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_35 (Dense)             (None, 3)                 195       
Total params: 8,739
Trainable params: 8,739
Non-trainable params: 0
____________________________________________________

In [38]:
filepath="E:\\Study\\Ph.D\\Publication\\EDL\\ML modelling related files"
filename=filepath+"3D32_2d64_relu_ALL.h5"
checkpointer = ModelCheckpoint( monitor='val_loss',filepath=filename, verbose=1, save_best_only=True)
history3=model.fit(x_train,y_train, validation_data=(x_cv, y_cv), epochs=1500, batch_size=16, callbacks=[checkpointer])

Epoch 1/1500
141/141 [==============================] - 4s 12ms/step - loss: 22664.3659 - MSE: 22664.3659 - val_loss: 1613.9600 - val_MSE: 1613.9600

Epoch 00001: val_loss improved from inf to 1613.95996, saving model to E:\Study\Ph.D\Publication\EDL\ML modelling related files3D32_2d64_relu_ALL.h5
Epoch 2/1500
141/141 [==============================] - 1s 8ms/step - loss: 1580.9779 - MSE: 1580.9779 - val_loss: 1180.8993 - val_MSE: 1180.8993

Epoch 00002: val_loss improved from 1613.95996 to 1180.89929, saving model to E:\Study\Ph.D\Publication\EDL\ML modelling related files3D32_2d64_relu_ALL.h5
Epoch 3/1500
141/141 [==============================] - 1s 8ms/step - loss: 1066.4182 - MSE: 1066.4182 - val_loss: 1013.6926 - val_MSE: 1013.6926

Epoch 00003: val_loss improved from 1180.89929 to 1013.69263, saving model to E:\Study\Ph.D\Publication\EDL\ML modelling related files3D32_2d64_relu_ALL.h5
Epoch 4/1500
141/141 [==============================] - 1s 9ms/step - loss: 1086.4560 - MSE: 10

Epoch 34/1500
141/141 [==============================] - 1s 8ms/step - loss: 349.7796 - MSE: 349.7796 - val_loss: 349.4695 - val_MSE: 349.4695

Epoch 00034: val_loss did not improve from 346.22879
Epoch 35/1500
141/141 [==============================] - 1s 8ms/step - loss: 399.8688 - MSE: 399.8688 - val_loss: 401.5255 - val_MSE: 401.5255

Epoch 00035: val_loss did not improve from 346.22879
Epoch 36/1500
141/141 [==============================] - 1s 8ms/step - loss: 356.8862 - MSE: 356.8862 - val_loss: 421.1308 - val_MSE: 421.1308

Epoch 00036: val_loss did not improve from 346.22879
Epoch 37/1500
141/141 [==============================] - 1s 8ms/step - loss: 374.5532 - MSE: 374.5532 - val_loss: 436.9595 - val_MSE: 436.9595

Epoch 00037: val_loss did not improve from 346.22879
Epoch 38/1500
141/141 [==============================] - 1s 8ms/step - loss: 424.6053 - MSE: 424.6053 - val_loss: 352.9364 - val_MSE: 352.9364

Epoch 00038: val_loss did not improve from 346.22879
Epoch 39/1500
1

141/141 [==============================] - 1s 8ms/step - loss: 319.0614 - MSE: 319.0614 - val_loss: 362.1568 - val_MSE: 362.1568

Epoch 00072: val_loss did not improve from 314.78421
Epoch 73/1500
141/141 [==============================] - 1s 8ms/step - loss: 282.1558 - MSE: 282.1558 - val_loss: 347.0042 - val_MSE: 347.0042

Epoch 00073: val_loss did not improve from 314.78421
Epoch 74/1500
141/141 [==============================] - 1s 8ms/step - loss: 295.3218 - MSE: 295.3218 - val_loss: 405.0544 - val_MSE: 405.0544

Epoch 00074: val_loss did not improve from 314.78421
Epoch 75/1500
141/141 [==============================] - 1s 8ms/step - loss: 296.2674 - MSE: 296.2674 - val_loss: 357.6578 - val_MSE: 357.6578

Epoch 00075: val_loss did not improve from 314.78421
Epoch 76/1500
141/141 [==============================] - 1s 8ms/step - loss: 271.0011 - MSE: 271.0011 - val_loss: 322.3716 - val_MSE: 322.3716

Epoch 00076: val_loss did not improve from 314.78421
Epoch 77/1500
141/141 [======


Epoch 00109: val_loss did not improve from 264.19922
Epoch 110/1500
141/141 [==============================] - 1s 9ms/step - loss: 243.4889 - MSE: 243.4889 - val_loss: 266.5740 - val_MSE: 266.5740

Epoch 00110: val_loss did not improve from 264.19922
Epoch 111/1500
141/141 [==============================] - 1s 8ms/step - loss: 238.5181 - MSE: 238.5181 - val_loss: 319.9163 - val_MSE: 319.9163

Epoch 00111: val_loss did not improve from 264.19922
Epoch 112/1500
141/141 [==============================] - 1s 8ms/step - loss: 324.3174 - MSE: 324.3174 - val_loss: 316.0370 - val_MSE: 316.0370

Epoch 00112: val_loss did not improve from 264.19922
Epoch 113/1500
141/141 [==============================] - 1s 8ms/step - loss: 191.5289 - MSE: 191.5289 - val_loss: 306.6042 - val_MSE: 306.6042

Epoch 00113: val_loss did not improve from 264.19922
Epoch 114/1500
141/141 [==============================] - 1s 8ms/step - loss: 226.3404 - MSE: 226.3404 - val_loss: 316.1476 - val_MSE: 316.1476

Epoch 001


Epoch 00147: val_loss did not improve from 222.63222
Epoch 148/1500
141/141 [==============================] - 1s 8ms/step - loss: 224.3207 - MSE: 224.3207 - val_loss: 261.4983 - val_MSE: 261.4983

Epoch 00148: val_loss did not improve from 222.63222
Epoch 149/1500
141/141 [==============================] - 1s 8ms/step - loss: 184.3626 - MSE: 184.3626 - val_loss: 241.5697 - val_MSE: 241.5697

Epoch 00149: val_loss did not improve from 222.63222
Epoch 150/1500
141/141 [==============================] - ETA: 0s - loss: 250.7401 - MSE: 250.740 - 1s 8ms/step - loss: 250.3727 - MSE: 250.3727 - val_loss: 280.6692 - val_MSE: 280.6692

Epoch 00150: val_loss did not improve from 222.63222
Epoch 151/1500
141/141 [==============================] - 1s 8ms/step - loss: 194.7611 - MSE: 194.7611 - val_loss: 240.8976 - val_MSE: 240.8976

Epoch 00151: val_loss did not improve from 222.63222
Epoch 152/1500
141/141 [==============================] - 1s 8ms/step - loss: 170.1446 - MSE: 170.1446 - val_los

141/141 [==============================] - 1s 8ms/step - loss: 174.8680 - MSE: 174.8680 - val_loss: 318.1040 - val_MSE: 318.1040

Epoch 00187: val_loss did not improve from 181.19783
Epoch 188/1500
141/141 [==============================] - 1s 8ms/step - loss: 185.7338 - MSE: 185.7338 - val_loss: 221.6294 - val_MSE: 221.6294

Epoch 00188: val_loss did not improve from 181.19783
Epoch 189/1500
141/141 [==============================] - 1s 8ms/step - loss: 167.2354 - MSE: 167.2354 - val_loss: 201.5054 - val_MSE: 201.5054

Epoch 00189: val_loss did not improve from 181.19783
Epoch 190/1500
141/141 [==============================] - 1s 8ms/step - loss: 190.8117 - MSE: 190.8117 - val_loss: 227.4471 - val_MSE: 227.4471

Epoch 00190: val_loss did not improve from 181.19783
Epoch 191/1500
141/141 [==============================] - 1s 8ms/step - loss: 192.0672 - MSE: 192.0672 - val_loss: 220.2886 - val_MSE: 220.2886

Epoch 00191: val_loss did not improve from 181.19783
Epoch 192/1500
141/141 [=

141/141 [==============================] - 1s 8ms/step - loss: 162.2959 - MSE: 162.2959 - val_loss: 226.1335 - val_MSE: 226.1335

Epoch 00228: val_loss did not improve from 163.14760
Epoch 229/1500
141/141 [==============================] - 1s 8ms/step - loss: 162.9530 - MSE: 162.9530 - val_loss: 196.8195 - val_MSE: 196.8195

Epoch 00229: val_loss did not improve from 163.14760
Epoch 230/1500
141/141 [==============================] - 1s 8ms/step - loss: 129.7944 - MSE: 129.7944 - val_loss: 200.9496 - val_MSE: 200.9496

Epoch 00230: val_loss did not improve from 163.14760
Epoch 231/1500
141/141 [==============================] - 1s 8ms/step - loss: 162.1828 - MSE: 162.1828 - val_loss: 193.8827 - val_MSE: 193.8827

Epoch 00231: val_loss did not improve from 163.14760
Epoch 232/1500
141/141 [==============================] - 1s 8ms/step - loss: 150.4208 - MSE: 150.4208 - val_loss: 249.6333 - val_MSE: 249.6333

Epoch 00232: val_loss did not improve from 163.14760
Epoch 233/1500
141/141 [=

141/141 [==============================] - 1s 8ms/step - loss: 175.5344 - MSE: 175.5344 - val_loss: 202.7453 - val_MSE: 202.7453

Epoch 00268: val_loss did not improve from 154.40105
Epoch 269/1500
141/141 [==============================] - 1s 8ms/step - loss: 207.1835 - MSE: 207.1835 - val_loss: 220.4677 - val_MSE: 220.4677

Epoch 00269: val_loss did not improve from 154.40105
Epoch 270/1500
141/141 [==============================] - 1s 8ms/step - loss: 197.1005 - MSE: 197.1005 - val_loss: 187.9164 - val_MSE: 187.9164

Epoch 00270: val_loss did not improve from 154.40105
Epoch 271/1500
141/141 [==============================] - 1s 8ms/step - loss: 178.0662 - MSE: 178.0662 - val_loss: 294.3171 - val_MSE: 294.3171

Epoch 00271: val_loss did not improve from 154.40105
Epoch 272/1500
141/141 [==============================] - 1s 8ms/step - loss: 192.7538 - MSE: 192.7538 - val_loss: 173.1228 - val_MSE: 173.1228

Epoch 00272: val_loss did not improve from 154.40105
Epoch 273/1500
141/141 [=

141/141 [==============================] - 1s 8ms/step - loss: 166.9449 - MSE: 166.9449 - val_loss: 213.0608 - val_MSE: 213.0608

Epoch 00308: val_loss did not improve from 146.41393
Epoch 309/1500
141/141 [==============================] - 1s 9ms/step - loss: 132.7566 - MSE: 132.7566 - val_loss: 190.5056 - val_MSE: 190.5056

Epoch 00309: val_loss did not improve from 146.41393
Epoch 310/1500
141/141 [==============================] - 1s 8ms/step - loss: 151.7111 - MSE: 151.7111 - val_loss: 239.1732 - val_MSE: 239.1732

Epoch 00310: val_loss did not improve from 146.41393
Epoch 311/1500
141/141 [==============================] - 1s 8ms/step - loss: 170.6134 - MSE: 170.6134 - val_loss: 200.9582 - val_MSE: 200.9582

Epoch 00311: val_loss did not improve from 146.41393
Epoch 312/1500
141/141 [==============================] - 1s 8ms/step - loss: 195.4904 - MSE: 195.4904 - val_loss: 199.6565 - val_MSE: 199.6565

Epoch 00312: val_loss did not improve from 146.41393
Epoch 313/1500
141/141 [=

141/141 [==============================] - 1s 9ms/step - loss: 196.0507 - MSE: 196.0507 - val_loss: 197.4653 - val_MSE: 197.4653

Epoch 00349: val_loss did not improve from 133.49208
Epoch 350/1500
141/141 [==============================] - 1s 10ms/step - loss: 182.7682 - MSE: 182.7682 - val_loss: 162.4552 - val_MSE: 162.4552

Epoch 00350: val_loss did not improve from 133.49208
Epoch 351/1500
141/141 [==============================] - 1s 9ms/step - loss: 204.1739 - MSE: 204.1739 - val_loss: 209.6387 - val_MSE: 209.6387

Epoch 00351: val_loss did not improve from 133.49208
Epoch 352/1500
141/141 [==============================] - 2s 11ms/step - loss: 145.0096 - MSE: 145.0096 - val_loss: 189.2544 - val_MSE: 189.2544

Epoch 00352: val_loss did not improve from 133.49208
Epoch 353/1500
141/141 [==============================] - 2s 12ms/step - loss: 205.2094 - MSE: 205.2094 - val_loss: 190.2306 - val_MSE: 190.2306

Epoch 00353: val_loss did not improve from 133.49208
Epoch 354/1500
141/141

141/141 [==============================] - 1s 10ms/step - loss: 198.9722 - MSE: 198.9722 - val_loss: 162.1755 - val_MSE: 162.1755

Epoch 00390: val_loss did not improve from 124.05721
Epoch 391/1500
141/141 [==============================] - 1s 11ms/step - loss: 160.9477 - MSE: 160.9477 - val_loss: 205.9639 - val_MSE: 205.9639

Epoch 00391: val_loss did not improve from 124.05721
Epoch 392/1500
141/141 [==============================] - 1s 9ms/step - loss: 169.1507 - MSE: 169.1507 - val_loss: 157.2379 - val_MSE: 157.2379

Epoch 00392: val_loss did not improve from 124.05721
Epoch 393/1500
141/141 [==============================] - 1s 8ms/step - loss: 169.1686 - MSE: 169.1686 - val_loss: 161.3883 - val_MSE: 161.3883

Epoch 00393: val_loss did not improve from 124.05721
Epoch 394/1500
141/141 [==============================] - 1s 9ms/step - loss: 159.7484 - MSE: 159.7484 - val_loss: 171.9056 - val_MSE: 171.9056

Epoch 00394: val_loss did not improve from 124.05721
Epoch 395/1500
141/141 

141/141 [==============================] - 1s 8ms/step - loss: 170.2589 - MSE: 170.2589 - val_loss: 164.6813 - val_MSE: 164.6813

Epoch 00431: val_loss did not improve from 121.16376
Epoch 432/1500
141/141 [==============================] - 1s 8ms/step - loss: 128.7353 - MSE: 128.7353 - val_loss: 158.2454 - val_MSE: 158.2454

Epoch 00432: val_loss did not improve from 121.16376
Epoch 433/1500
141/141 [==============================] - 1s 8ms/step - loss: 145.7481 - MSE: 145.7481 - val_loss: 150.6102 - val_MSE: 150.6102

Epoch 00433: val_loss did not improve from 121.16376
Epoch 434/1500
141/141 [==============================] - 1s 8ms/step - loss: 159.7560 - MSE: 159.7560 - val_loss: 163.0621 - val_MSE: 163.0621

Epoch 00434: val_loss did not improve from 121.16376
Epoch 435/1500
141/141 [==============================] - 1s 7ms/step - loss: 136.1892 - MSE: 136.1892 - val_loss: 125.0570 - val_MSE: 125.0570

Epoch 00435: val_loss did not improve from 121.16376
Epoch 436/1500
141/141 [=

141/141 [==============================] - 1s 8ms/step - loss: 138.1652 - MSE: 138.1652 - val_loss: 137.2661 - val_MSE: 137.2661

Epoch 00471: val_loss did not improve from 112.32374
Epoch 472/1500
141/141 [==============================] - 1s 7ms/step - loss: 137.9791 - MSE: 137.9791 - val_loss: 162.3009 - val_MSE: 162.3009

Epoch 00472: val_loss did not improve from 112.32374
Epoch 473/1500
141/141 [==============================] - 1s 8ms/step - loss: 165.1283 - MSE: 165.1283 - val_loss: 169.9800 - val_MSE: 169.9800

Epoch 00473: val_loss did not improve from 112.32374
Epoch 474/1500
141/141 [==============================] - 1s 8ms/step - loss: 133.7392 - MSE: 133.7392 - val_loss: 153.2080 - val_MSE: 153.2080

Epoch 00474: val_loss did not improve from 112.32374
Epoch 475/1500
141/141 [==============================] - 1s 8ms/step - loss: 71.9066 - MSE: 71.9066 - val_loss: 163.1608 - val_MSE: 163.1608

Epoch 00475: val_loss did not improve from 112.32374
Epoch 476/1500
141/141 [===

141/141 [==============================] - 1s 7ms/step - loss: 147.5207 - MSE: 147.5207 - val_loss: 195.2802 - val_MSE: 195.2802

Epoch 00512: val_loss did not improve from 112.05428
Epoch 513/1500
141/141 [==============================] - 1s 7ms/step - loss: 134.5910 - MSE: 134.5910 - val_loss: 179.2139 - val_MSE: 179.2139

Epoch 00513: val_loss did not improve from 112.05428
Epoch 514/1500
141/141 [==============================] - 1s 8ms/step - loss: 104.4558 - MSE: 104.4558 - val_loss: 170.3941 - val_MSE: 170.3941

Epoch 00514: val_loss did not improve from 112.05428
Epoch 515/1500
141/141 [==============================] - 1s 7ms/step - loss: 109.4502 - MSE: 109.4502 - val_loss: 275.8244 - val_MSE: 275.8244

Epoch 00515: val_loss did not improve from 112.05428
Epoch 516/1500
141/141 [==============================] - 1s 7ms/step - loss: 247.5867 - MSE: 247.5867 - val_loss: 216.8529 - val_MSE: 216.8529

Epoch 00516: val_loss did not improve from 112.05428
Epoch 517/1500
141/141 [=

141/141 [==============================] - 1s 8ms/step - loss: 79.4413 - MSE: 79.4413 - val_loss: 138.7247 - val_MSE: 138.7247

Epoch 00553: val_loss did not improve from 101.69615
Epoch 554/1500
141/141 [==============================] - 1s 8ms/step - loss: 109.7088 - MSE: 109.7088 - val_loss: 124.3061 - val_MSE: 124.3061

Epoch 00554: val_loss did not improve from 101.69615
Epoch 555/1500
141/141 [==============================] - 1s 7ms/step - loss: 110.7055 - MSE: 110.7055 - val_loss: 150.8133 - val_MSE: 150.8133

Epoch 00555: val_loss did not improve from 101.69615
Epoch 556/1500
141/141 [==============================] - 1s 8ms/step - loss: 111.0482 - MSE: 111.0482 - val_loss: 124.2143 - val_MSE: 124.2143

Epoch 00556: val_loss did not improve from 101.69615
Epoch 557/1500
141/141 [==============================] - 1s 7ms/step - loss: 65.9809 - MSE: 65.9809 - val_loss: 144.3306 - val_MSE: 144.3306

Epoch 00557: val_loss did not improve from 101.69615
Epoch 558/1500
141/141 [=====

141/141 [==============================] - 1s 8ms/step - loss: 94.6276 - MSE: 94.6276 - val_loss: 167.1690 - val_MSE: 167.1690

Epoch 00594: val_loss did not improve from 91.61790
Epoch 595/1500
141/141 [==============================] - 1s 8ms/step - loss: 101.5462 - MSE: 101.5462 - val_loss: 145.4956 - val_MSE: 145.4956

Epoch 00595: val_loss did not improve from 91.61790
Epoch 596/1500
141/141 [==============================] - 1s 8ms/step - loss: 80.8174 - MSE: 80.8174 - val_loss: 153.9274 - val_MSE: 153.9274

Epoch 00596: val_loss did not improve from 91.61790
Epoch 597/1500
141/141 [==============================] - 1s 8ms/step - loss: 109.6224 - MSE: 109.6224 - val_loss: 163.5374 - val_MSE: 163.5374

Epoch 00597: val_loss did not improve from 91.61790
Epoch 598/1500
141/141 [==============================] - 1s 8ms/step - loss: 98.9934 - MSE: 98.9934 - val_loss: 143.2254 - val_MSE: 143.2254

Epoch 00598: val_loss did not improve from 91.61790
Epoch 599/1500
141/141 [============

141/141 [==============================] - 1s 8ms/step - loss: 94.0869 - MSE: 94.0869 - val_loss: 106.1966 - val_MSE: 106.1966

Epoch 00636: val_loss did not improve from 91.61790
Epoch 637/1500
141/141 [==============================] - 1s 8ms/step - loss: 92.9993 - MSE: 92.9993 - val_loss: 130.9310 - val_MSE: 130.9310

Epoch 00637: val_loss did not improve from 91.61790
Epoch 638/1500
141/141 [==============================] - 1s 8ms/step - loss: 107.7412 - MSE: 107.7412 - val_loss: 177.6373 - val_MSE: 177.6373

Epoch 00638: val_loss did not improve from 91.61790
Epoch 639/1500
141/141 [==============================] - 1s 8ms/step - loss: 137.9093 - MSE: 137.9093 - val_loss: 119.7856 - val_MSE: 119.7856

Epoch 00639: val_loss did not improve from 91.61790
Epoch 640/1500
141/141 [==============================] - 1s 8ms/step - loss: 132.0342 - MSE: 132.0342 - val_loss: 144.1562 - val_MSE: 144.1562

Epoch 00640: val_loss did not improve from 91.61790
Epoch 641/1500
141/141 [==========

141/141 [==============================] - 1s 8ms/step - loss: 113.0685 - MSE: 113.0685 - val_loss: 125.3150 - val_MSE: 125.3150

Epoch 00678: val_loss did not improve from 91.61790
Epoch 679/1500
141/141 [==============================] - 1s 8ms/step - loss: 49.4758 - MSE: 49.4758 - val_loss: 125.0898 - val_MSE: 125.0898

Epoch 00679: val_loss did not improve from 91.61790
Epoch 680/1500
141/141 [==============================] - 1s 8ms/step - loss: 70.5760 - MSE: 70.5760 - val_loss: 114.3706 - val_MSE: 114.3706

Epoch 00680: val_loss did not improve from 91.61790
Epoch 681/1500
141/141 [==============================] - 1s 8ms/step - loss: 89.2677 - MSE: 89.2677 - val_loss: 178.1401 - val_MSE: 178.1401

Epoch 00681: val_loss did not improve from 91.61790
Epoch 682/1500
141/141 [==============================] - 1s 8ms/step - loss: 91.6430 - MSE: 91.6430 - val_loss: 206.8882 - val_MSE: 206.8882

Epoch 00682: val_loss did not improve from 91.61790
Epoch 683/1500
141/141 [==============

Epoch 720/1500
141/141 [==============================] - 1s 8ms/step - loss: 108.2478 - MSE: 108.2478 - val_loss: 168.9190 - val_MSE: 168.9190

Epoch 00720: val_loss did not improve from 91.61790
Epoch 721/1500
141/141 [==============================] - 1s 8ms/step - loss: 76.2777 - MSE: 76.2777 - val_loss: 160.7515 - val_MSE: 160.7515

Epoch 00721: val_loss did not improve from 91.61790
Epoch 722/1500
141/141 [==============================] - 1s 8ms/step - loss: 88.7981 - MSE: 88.7981 - val_loss: 146.2091 - val_MSE: 146.2091

Epoch 00722: val_loss did not improve from 91.61790
Epoch 723/1500
141/141 [==============================] - 1s 8ms/step - loss: 134.8174 - MSE: 134.8174 - val_loss: 154.4633 - val_MSE: 154.4633

Epoch 00723: val_loss did not improve from 91.61790
Epoch 724/1500
141/141 [==============================] - 1s 8ms/step - loss: 80.8997 - MSE: 80.8997 - val_loss: 161.5347 - val_MSE: 161.5347

Epoch 00724: val_loss did not improve from 91.61790
Epoch 725/1500
141/14

141/141 [==============================] - 1s 9ms/step - loss: 87.3386 - MSE: 87.3386 - val_loss: 141.4436 - val_MSE: 141.4436

Epoch 00762: val_loss did not improve from 91.61790
Epoch 763/1500
141/141 [==============================] - 1s 9ms/step - loss: 175.6122 - MSE: 175.6122 - val_loss: 174.1343 - val_MSE: 174.1343

Epoch 00763: val_loss did not improve from 91.61790
Epoch 764/1500
141/141 [==============================] - 2s 11ms/step - loss: 144.6972 - MSE: 144.6972 - val_loss: 154.7485 - val_MSE: 154.7485

Epoch 00764: val_loss did not improve from 91.61790
Epoch 765/1500
141/141 [==============================] - 2s 11ms/step - loss: 103.2382 - MSE: 103.2382 - val_loss: 160.0278 - val_MSE: 160.0278

Epoch 00765: val_loss did not improve from 91.61790
Epoch 766/1500
141/141 [==============================] - 1s 9ms/step - loss: 75.3235 - MSE: 75.3235 - val_loss: 201.7082 - val_MSE: 201.7082

Epoch 00766: val_loss did not improve from 91.61790
Epoch 767/1500
141/141 [========

141/141 [==============================] - 1s 8ms/step - loss: 219.1015 - MSE: 219.1015 - val_loss: 170.2530 - val_MSE: 170.2530

Epoch 00804: val_loss did not improve from 91.61790
Epoch 805/1500
141/141 [==============================] - 1s 8ms/step - loss: 211.3537 - MSE: 211.3537 - val_loss: 182.9952 - val_MSE: 182.9952

Epoch 00805: val_loss did not improve from 91.61790
Epoch 806/1500
141/141 [==============================] - 1s 8ms/step - loss: 129.1606 - MSE: 129.1606 - val_loss: 162.5404 - val_MSE: 162.5404

Epoch 00806: val_loss did not improve from 91.61790
Epoch 807/1500
141/141 [==============================] - 1s 7ms/step - loss: 103.4268 - MSE: 103.4268 - val_loss: 199.6300 - val_MSE: 199.6300

Epoch 00807: val_loss did not improve from 91.61790
Epoch 808/1500
141/141 [==============================] - 1s 7ms/step - loss: 222.4656 - MSE: 222.4656 - val_loss: 177.9071 - val_MSE: 177.9071

Epoch 00808: val_loss did not improve from 91.61790
Epoch 809/1500
141/141 [======

Epoch 846/1500
141/141 [==============================] - 1s 8ms/step - loss: 77.2251 - MSE: 77.2251 - val_loss: 208.0761 - val_MSE: 208.0761

Epoch 00846: val_loss did not improve from 91.61790
Epoch 847/1500
141/141 [==============================] - 1s 7ms/step - loss: 195.2160 - MSE: 195.2160 - val_loss: 157.3511 - val_MSE: 157.3511

Epoch 00847: val_loss did not improve from 91.61790
Epoch 848/1500
141/141 [==============================] - 1s 9ms/step - loss: 75.0027 - MSE: 75.0027 - val_loss: 167.9584 - val_MSE: 167.9584

Epoch 00848: val_loss did not improve from 91.61790
Epoch 849/1500
141/141 [==============================] - 1s 7ms/step - loss: 107.0737 - MSE: 107.0737 - val_loss: 158.7106 - val_MSE: 158.7106

Epoch 00849: val_loss did not improve from 91.61790
Epoch 850/1500
141/141 [==============================] - 1s 8ms/step - loss: 61.4611 - MSE: 61.4611 - val_loss: 167.2463 - val_MSE: 167.2463

Epoch 00850: val_loss did not improve from 91.61790
Epoch 851/1500
141/14

141/141 [==============================] - 1s 7ms/step - loss: 162.3109 - MSE: 162.3109 - val_loss: 146.5730 - val_MSE: 146.5730

Epoch 00888: val_loss did not improve from 91.61790
Epoch 889/1500
141/141 [==============================] - 1s 8ms/step - loss: 66.5951 - MSE: 66.5951 - val_loss: 146.1049 - val_MSE: 146.1049

Epoch 00889: val_loss did not improve from 91.61790
Epoch 890/1500
141/141 [==============================] - 1s 9ms/step - loss: 73.6302 - MSE: 73.6302 - val_loss: 156.1616 - val_MSE: 156.1616

Epoch 00890: val_loss did not improve from 91.61790
Epoch 891/1500
141/141 [==============================] - 1s 8ms/step - loss: 118.9352 - MSE: 118.9352 - val_loss: 117.1306 - val_MSE: 117.1306

Epoch 00891: val_loss did not improve from 91.61790
Epoch 892/1500
141/141 [==============================] - 1s 7ms/step - loss: 82.0205 - MSE: 82.0205 - val_loss: 124.8805 - val_MSE: 124.8805

Epoch 00892: val_loss did not improve from 91.61790
Epoch 893/1500
141/141 [============

141/141 [==============================] - 1s 8ms/step - loss: 103.2224 - MSE: 103.2224 - val_loss: 129.0570 - val_MSE: 129.0570

Epoch 00930: val_loss did not improve from 91.61790
Epoch 931/1500
141/141 [==============================] - 1s 7ms/step - loss: 110.0477 - MSE: 110.0477 - val_loss: 157.3208 - val_MSE: 157.3208

Epoch 00931: val_loss did not improve from 91.61790
Epoch 932/1500
141/141 [==============================] - 1s 7ms/step - loss: 95.2638 - MSE: 95.2638 - val_loss: 134.8289 - val_MSE: 134.8289

Epoch 00932: val_loss did not improve from 91.61790
Epoch 933/1500
141/141 [==============================] - 1s 8ms/step - loss: 64.3138 - MSE: 64.3138 - val_loss: 165.5652 - val_MSE: 165.5652

Epoch 00933: val_loss did not improve from 91.61790
Epoch 934/1500
141/141 [==============================] - 1s 7ms/step - loss: 85.8392 - MSE: 85.8392 - val_loss: 172.7684 - val_MSE: 172.7684

Epoch 00934: val_loss did not improve from 91.61790
Epoch 935/1500
141/141 [============

141/141 [==============================] - 1s 7ms/step - loss: 90.0756 - MSE: 90.0756 - val_loss: 178.9990 - val_MSE: 178.9990

Epoch 00972: val_loss did not improve from 91.61790
Epoch 973/1500
141/141 [==============================] - 1s 8ms/step - loss: 123.6025 - MSE: 123.6025 - val_loss: 141.1337 - val_MSE: 141.1337

Epoch 00973: val_loss did not improve from 91.61790
Epoch 974/1500
141/141 [==============================] - 1s 8ms/step - loss: 126.8888 - MSE: 126.8888 - val_loss: 229.8984 - val_MSE: 229.8984

Epoch 00974: val_loss did not improve from 91.61790
Epoch 975/1500
141/141 [==============================] - 1s 7ms/step - loss: 99.0750 - MSE: 99.0750 - val_loss: 158.3025 - val_MSE: 158.3025

Epoch 00975: val_loss did not improve from 91.61790
Epoch 976/1500
141/141 [==============================] - 1s 7ms/step - loss: 78.8618 - MSE: 78.8618 - val_loss: 153.9589 - val_MSE: 153.9589

Epoch 00976: val_loss did not improve from 91.61790
Epoch 977/1500
141/141 [============


Epoch 01013: val_loss did not improve from 91.61790
Epoch 1014/1500
141/141 [==============================] - 1s 8ms/step - loss: 205.2142 - MSE: 205.2142 - val_loss: 142.1424 - val_MSE: 142.1424

Epoch 01014: val_loss did not improve from 91.61790
Epoch 1015/1500
141/141 [==============================] - 1s 8ms/step - loss: 82.8461 - MSE: 82.8461 - val_loss: 128.2032 - val_MSE: 128.2032

Epoch 01015: val_loss did not improve from 91.61790
Epoch 1016/1500
141/141 [==============================] - 1s 8ms/step - loss: 92.0580 - MSE: 92.0580 - val_loss: 121.9491 - val_MSE: 121.9491

Epoch 01016: val_loss did not improve from 91.61790
Epoch 1017/1500
141/141 [==============================] - 1s 8ms/step - loss: 87.7688 - MSE: 87.7688 - val_loss: 149.9198 - val_MSE: 149.9198

Epoch 01017: val_loss did not improve from 91.61790
Epoch 1018/1500
141/141 [==============================] - 1s 8ms/step - loss: 55.9551 - MSE: 55.9551 - val_loss: 117.9232 - val_MSE: 117.9232

Epoch 01018: val_

141/141 [==============================] - 1s 8ms/step - loss: 78.6228 - MSE: 78.6228 - val_loss: 256.9557 - val_MSE: 256.9557

Epoch 01055: val_loss did not improve from 91.61790
Epoch 1056/1500
141/141 [==============================] - 1s 10ms/step - loss: 241.2364 - MSE: 241.2364 - val_loss: 250.7727 - val_MSE: 250.7727

Epoch 01056: val_loss did not improve from 91.61790
Epoch 1057/1500
141/141 [==============================] - 2s 11ms/step - loss: 92.8616 - MSE: 92.8616 - val_loss: 111.9532 - val_MSE: 111.9532

Epoch 01057: val_loss did not improve from 91.61790
Epoch 1058/1500
141/141 [==============================] - 2s 11ms/step - loss: 111.8055 - MSE: 111.8055 - val_loss: 178.2219 - val_MSE: 178.2219

Epoch 01058: val_loss did not improve from 91.61790
Epoch 1059/1500
141/141 [==============================] - 1s 10ms/step - loss: 56.2107 - MSE: 56.2107 - val_loss: 149.8283 - val_MSE: 149.8283

Epoch 01059: val_loss did not improve from 91.61790
Epoch 1060/1500
141/141 [===


Epoch 01096: val_loss did not improve from 91.61790
Epoch 1097/1500
141/141 [==============================] - 1s 8ms/step - loss: 34.4911 - MSE: 34.4911 - val_loss: 204.2171 - val_MSE: 204.2171

Epoch 01097: val_loss did not improve from 91.61790
Epoch 1098/1500
141/141 [==============================] - 1s 8ms/step - loss: 78.9844 - MSE: 78.9844 - val_loss: 136.3588 - val_MSE: 136.3588

Epoch 01098: val_loss did not improve from 91.61790
Epoch 1099/1500
141/141 [==============================] - 1s 8ms/step - loss: 93.9169 - MSE: 93.9169 - val_loss: 135.9404 - val_MSE: 135.9404

Epoch 01099: val_loss did not improve from 91.61790
Epoch 1100/1500
141/141 [==============================] - 1s 8ms/step - loss: 69.4257 - MSE: 69.4257 - val_loss: 135.5109 - val_MSE: 135.5109

Epoch 01100: val_loss did not improve from 91.61790
Epoch 1101/1500
141/141 [==============================] - 1s 8ms/step - loss: 36.5728 - MSE: 36.5728 - val_loss: 127.5153 - val_MSE: 127.5153

Epoch 01101: val_lo

141/141 [==============================] - 1s 8ms/step - loss: 61.4128 - MSE: 61.4128 - val_loss: 177.8002 - val_MSE: 177.8002

Epoch 01138: val_loss did not improve from 91.61790
Epoch 1139/1500
141/141 [==============================] - 1s 8ms/step - loss: 77.4460 - MSE: 77.4460 - val_loss: 171.3206 - val_MSE: 171.3206

Epoch 01139: val_loss did not improve from 91.61790
Epoch 1140/1500
141/141 [==============================] - 1s 9ms/step - loss: 71.8329 - MSE: 71.8329 - val_loss: 157.5550 - val_MSE: 157.5550

Epoch 01140: val_loss did not improve from 91.61790
Epoch 1141/1500
141/141 [==============================] - 1s 7ms/step - loss: 75.8886 - MSE: 75.8886 - val_loss: 182.8299 - val_MSE: 182.8299

Epoch 01141: val_loss did not improve from 91.61790
Epoch 1142/1500
141/141 [==============================] - 1s 7ms/step - loss: 78.2405 - MSE: 78.2405 - val_loss: 171.3515 - val_MSE: 171.3515

Epoch 01142: val_loss did not improve from 91.61790
Epoch 1143/1500
141/141 [===========

141/141 [==============================] - 1s 8ms/step - loss: 89.9403 - MSE: 89.9403 - val_loss: 151.6960 - val_MSE: 151.6960

Epoch 01180: val_loss did not improve from 91.61790
Epoch 1181/1500
141/141 [==============================] - 1s 8ms/step - loss: 95.9968 - MSE: 95.9968 - val_loss: 153.0949 - val_MSE: 153.0949

Epoch 01181: val_loss did not improve from 91.61790
Epoch 1182/1500
141/141 [==============================] - 1s 7ms/step - loss: 82.7993 - MSE: 82.7993 - val_loss: 165.3088 - val_MSE: 165.3088

Epoch 01182: val_loss did not improve from 91.61790
Epoch 1183/1500
141/141 [==============================] - 1s 8ms/step - loss: 63.8268 - MSE: 63.8268 - val_loss: 205.6727 - val_MSE: 205.6727

Epoch 01183: val_loss did not improve from 91.61790
Epoch 1184/1500
141/141 [==============================] - 1s 8ms/step - loss: 114.8597 - MSE: 114.8597 - val_loss: 149.2861 - val_MSE: 149.2861

Epoch 01184: val_loss did not improve from 91.61790
Epoch 1185/1500
141/141 [=========

141/141 [==============================] - 1s 8ms/step - loss: 82.2384 - MSE: 82.2384 - val_loss: 244.2658 - val_MSE: 244.2658

Epoch 01222: val_loss did not improve from 91.61790
Epoch 1223/1500
141/141 [==============================] - 1s 8ms/step - loss: 98.8664 - MSE: 98.8664 - val_loss: 163.8094 - val_MSE: 163.8094

Epoch 01223: val_loss did not improve from 91.61790
Epoch 1224/1500
141/141 [==============================] - 1s 8ms/step - loss: 77.2384 - MSE: 77.2384 - val_loss: 175.6581 - val_MSE: 175.6581

Epoch 01224: val_loss did not improve from 91.61790
Epoch 1225/1500
141/141 [==============================] - 1s 8ms/step - loss: 82.9961 - MSE: 82.9961 - val_loss: 170.4103 - val_MSE: 170.4103

Epoch 01225: val_loss did not improve from 91.61790
Epoch 1226/1500
141/141 [==============================] - 1s 8ms/step - loss: 101.7296 - MSE: 101.7296 - val_loss: 162.2138 - val_MSE: 162.2138

Epoch 01226: val_loss did not improve from 91.61790
Epoch 1227/1500
141/141 [=========

141/141 [==============================] - 1s 8ms/step - loss: 120.0088 - MSE: 120.0088 - val_loss: 153.6537 - val_MSE: 153.6537

Epoch 01264: val_loss did not improve from 91.61790
Epoch 1265/1500
141/141 [==============================] - 1s 8ms/step - loss: 58.7262 - MSE: 58.7262 - val_loss: 187.0871 - val_MSE: 187.0871

Epoch 01265: val_loss did not improve from 91.61790
Epoch 1266/1500
141/141 [==============================] - 1s 8ms/step - loss: 77.6580 - MSE: 77.6580 - val_loss: 172.1053 - val_MSE: 172.1053

Epoch 01266: val_loss did not improve from 91.61790
Epoch 1267/1500
141/141 [==============================] - 1s 8ms/step - loss: 79.9807 - MSE: 79.9807 - val_loss: 183.2318 - val_MSE: 183.2318

Epoch 01267: val_loss did not improve from 91.61790
Epoch 1268/1500
141/141 [==============================] - 1s 9ms/step - loss: 43.4870 - MSE: 43.4870 - val_loss: 189.0346 - val_MSE: 189.0346

Epoch 01268: val_loss did not improve from 91.61790
Epoch 1269/1500
141/141 [=========

141/141 [==============================] - 1s 7ms/step - loss: 71.1741 - MSE: 71.1741 - val_loss: 153.1491 - val_MSE: 153.1491

Epoch 01306: val_loss did not improve from 91.61790
Epoch 1307/1500
141/141 [==============================] - 1s 7ms/step - loss: 77.6532 - MSE: 77.6532 - val_loss: 151.1482 - val_MSE: 151.1482

Epoch 01307: val_loss did not improve from 91.61790
Epoch 1308/1500
141/141 [==============================] - 1s 8ms/step - loss: 47.6519 - MSE: 47.6519 - val_loss: 156.2716 - val_MSE: 156.2716

Epoch 01308: val_loss did not improve from 91.61790
Epoch 1309/1500
141/141 [==============================] - 1s 7ms/step - loss: 90.6320 - MSE: 90.6320 - val_loss: 167.9751 - val_MSE: 167.9751

Epoch 01309: val_loss did not improve from 91.61790
Epoch 1310/1500
141/141 [==============================] - 1s 7ms/step - loss: 96.7568 - MSE: 96.7568 - val_loss: 163.7869 - val_MSE: 163.7869

Epoch 01310: val_loss did not improve from 91.61790
Epoch 1311/1500
141/141 [===========

141/141 [==============================] - 1s 9ms/step - loss: 62.8353 - MSE: 62.8353 - val_loss: 178.7778 - val_MSE: 178.7778

Epoch 01348: val_loss did not improve from 91.61790
Epoch 1349/1500
141/141 [==============================] - 1s 8ms/step - loss: 64.7544 - MSE: 64.7544 - val_loss: 181.2210 - val_MSE: 181.2210

Epoch 01349: val_loss did not improve from 91.61790
Epoch 1350/1500
141/141 [==============================] - 1s 8ms/step - loss: 48.8835 - MSE: 48.8835 - val_loss: 159.1306 - val_MSE: 159.1306

Epoch 01350: val_loss did not improve from 91.61790
Epoch 1351/1500
141/141 [==============================] - 1s 8ms/step - loss: 59.1912 - MSE: 59.1912 - val_loss: 166.3796 - val_MSE: 166.3796

Epoch 01351: val_loss did not improve from 91.61790
Epoch 1352/1500
141/141 [==============================] - 1s 7ms/step - loss: 53.1827 - MSE: 53.1827 - val_loss: 175.6657 - val_MSE: 175.6657

Epoch 01352: val_loss did not improve from 91.61790
Epoch 1353/1500
141/141 [===========

141/141 [==============================] - 1s 8ms/step - loss: 64.0422 - MSE: 64.0422 - val_loss: 160.6931 - val_MSE: 160.6931

Epoch 01390: val_loss did not improve from 91.61790
Epoch 1391/1500
141/141 [==============================] - 1s 7ms/step - loss: 35.4137 - MSE: 35.4137 - val_loss: 150.7921 - val_MSE: 150.7921

Epoch 01391: val_loss did not improve from 91.61790
Epoch 1392/1500
141/141 [==============================] - 1s 8ms/step - loss: 67.3190 - MSE: 67.3190 - val_loss: 163.2545 - val_MSE: 163.2545

Epoch 01392: val_loss did not improve from 91.61790
Epoch 1393/1500
141/141 [==============================] - 1s 8ms/step - loss: 57.7041 - MSE: 57.7041 - val_loss: 210.5717 - val_MSE: 210.5717

Epoch 01393: val_loss did not improve from 91.61790
Epoch 1394/1500
141/141 [==============================] - 1s 8ms/step - loss: 56.2893 - MSE: 56.2893 - val_loss: 190.8042 - val_MSE: 190.8042

Epoch 01394: val_loss did not improve from 91.61790
Epoch 1395/1500
141/141 [===========

141/141 [==============================] - 1s 7ms/step - loss: 118.1139 - MSE: 118.1139 - val_loss: 182.0285 - val_MSE: 182.0285

Epoch 01432: val_loss did not improve from 91.61790
Epoch 1433/1500
141/141 [==============================] - 1s 8ms/step - loss: 64.3311 - MSE: 64.3311 - val_loss: 167.8849 - val_MSE: 167.8849

Epoch 01433: val_loss did not improve from 91.61790
Epoch 1434/1500
141/141 [==============================] - 1s 8ms/step - loss: 77.5659 - MSE: 77.5659 - val_loss: 181.3445 - val_MSE: 181.3445

Epoch 01434: val_loss did not improve from 91.61790
Epoch 1435/1500
141/141 [==============================] - 1s 8ms/step - loss: 51.1660 - MSE: 51.1660 - val_loss: 206.0607 - val_MSE: 206.0607

Epoch 01435: val_loss did not improve from 91.61790
Epoch 1436/1500
141/141 [==============================] - 1s 8ms/step - loss: 77.2554 - MSE: 77.2554 - val_loss: 160.4703 - val_MSE: 160.4703

Epoch 01436: val_loss did not improve from 91.61790
Epoch 1437/1500
141/141 [=========

141/141 [==============================] - 1s 8ms/step - loss: 53.0119 - MSE: 53.0119 - val_loss: 158.8151 - val_MSE: 158.8151

Epoch 01474: val_loss did not improve from 91.61790
Epoch 1475/1500
141/141 [==============================] - 1s 8ms/step - loss: 49.5339 - MSE: 49.5339 - val_loss: 151.4277 - val_MSE: 151.4277

Epoch 01475: val_loss did not improve from 91.61790
Epoch 1476/1500
141/141 [==============================] - 1s 8ms/step - loss: 51.4687 - MSE: 51.4687 - val_loss: 167.8572 - val_MSE: 167.8572

Epoch 01476: val_loss did not improve from 91.61790
Epoch 1477/1500
141/141 [==============================] - 1s 8ms/step - loss: 73.4298 - MSE: 73.4298 - val_loss: 140.2355 - val_MSE: 140.2355

Epoch 01477: val_loss did not improve from 91.61790
Epoch 1478/1500
141/141 [==============================] - 1s 8ms/step - loss: 39.5808 - MSE: 39.5808 - val_loss: 142.8461 - val_MSE: 142.8461

Epoch 01478: val_loss did not improve from 91.61790
Epoch 1479/1500
141/141 [===========

In [36]:
minloss=round(min(history3.history['val_loss']), 1) 
modelfilepath = filepath +  '\\history_loss_relu'
df=pd.DataFrame(history3.history)
# model.save(modelfilepath+'.h5')
df.to_csv(modelfilepath+'.csv')

In [70]:
model = Sequential()
model.add(LSTM(64, return_sequences=False, input_shape=(x_traindim[1].shape)))
# model.add(LSTM(64, return_sequences=True))
model.add(LSTM(64))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
# model.add(Dense(128, activation='relu'))
# model.add(Dense(512, activation='relu'))
# model.add(Dense(128, activation='relu'))
# model.add(Dense(64, activation='relu'))
# model.add(Dense(128, activation='relu'))
# model.add(Dense(64, activation='relu'))
# model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
# model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='linear'))
opt=keras.optimizers.adam(0.001)
model.compile(loss='mean_squared_error', optimizer=opt, metrics=['MSE'])
model.summary()

ValueError: Input 0 is incompatible with layer lstm_53: expected ndim=3, found ndim=2

In [74]:
filepath="E:\\Simulations\\Silvaco\\\\2D HEMT\\EDL\\DATA for modeling\\models_history\\FOM_MSE_withGANdata_noDropoutused26july.hdf5"
checkpointer = ModelCheckpoint( monitor='val_loss',filepath=filepath, verbose=1, save_best_only=True)
history3=model.fit(x_traindim,y_train, validation_data=(x_cvdim, y_cv), epochs=10, batch_size=16, callbacks=[checkpointer])


Train on 2247 samples, validate on 397 samples
Epoch 1/10
2247/2247 [==============================] - 22s 10ms/step - loss: 15482.2082 - mean_squared_error: 15482.2082 - val_loss: 1121.5093 - val_mean_squared_error: 1121.5093

Epoch 00001: val_loss improved from inf to 1121.50926, saving model to E:\Simulations\Silvaco\\2D HEMT\EDL\DATA for modeling\models_history\FOM_MSE_withGANdata_noDropoutused26july.hdf5
Epoch 2/10
2247/2247 [==============================] - 4s 2ms/step - loss: 1105.7519 - mean_squared_error: 1105.7519 - val_loss: 943.9846 - val_mean_squared_error: 943.9846

Epoch 00002: val_loss improved from 1121.50926 to 943.98458, saving model to E:\Simulations\Silvaco\\2D HEMT\EDL\DATA for modeling\models_history\FOM_MSE_withGANdata_noDropoutused26july.hdf5
Epoch 3/10
2247/2247 [==============================] - 4s 2ms/step - loss: 983.5061 - mean_squared_error: 983.5061 - val_loss: 906.2233 - val_mean_squared_error: 906.2233

Epoch 00003: val_loss improved from 943.98458 to

In [ ]:
xpred=[]
act=[]
m=0
for i in range(467):
    r=model.predict(np.expand_dims(x_testdim[i,:], axis=0))
#     pred.append(r[0][0])
#     act.append(y_test[i])
#     print((r[0]-y_test[i])/y_test[i], r[0][0], y_test[i] )
#     print('predicted: ', y_test[i],' actual: ', r, 'diff:', (r[0]-y_test[i])/y_test[i]*100)

    if (np.max((r[0]-y_test[i])/y_test[i]*100)>10):
        print('predicted: ', y_test[i],' actual: ', r, 'diff:', (r[0]-y_test[i])/y_test[i]*100)
        m=m+1
m

In [84]:
minloss=round(min(history3.history['val_loss']), 1)
minloss

748.5

In [ ]:
import pandas as pd
df_hist=pd.DataFrame(history3.history)
df_hist.to_csv("E:\\Simulations\\Silvaco\\2D HEMT\\EDL\\DATA for modeling\\historyforVth.csv")

In [ ]:
df1=pd.DataFrame(list(zip(pred, act)), columns=['Pred', 'Act'])
df1.to_csv('act_pred_SS.csv')

In [49]:
import pandas as pd
df=pd.DataFrame(history3.history)

In [50]:
df.to_csv("E:\\Simulations\\Silvaco\\\\2D HEMT\\EDL\\DATA for modeling\\new_models_and_their_history\\L32_L32_L256_2D64_D3_46.csv")
model.save("E:\\Simulations\\Silvaco\\2D HEMT\\EDL\\DATA for modeling\\new_models_and_their_history\\L32_L32_L256_2D64_D3_46.h5")

In [ ]:
# for i in range(50):
r=model.predict(x_test[1,:])
#     print(y_test[i])
print('predicted: ', y_test[1],' actual: ', r )


In [ ]:
for i in range(len(X_test)):
    print(r[i]*1000,y_test[i]*1000)

In [ ]:
model = Sequential()
adam=optimizers.Adam(lr=0.01, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)

model.add(Conv1D(filters=32, kernel_size=1, activation='relu', input_shape=(x_traindim[0].shape)))
model.add(Dropout(0.5))


model.add(MaxPooling1D(pool_size=1))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='linear'))

model.compile(loss='mean_squared_error', optimizer=adam, metrics=['MSE'])
model.summary()

In [ ]:
filepath="E:\\Simulations\\Silvaco\\2D HEMT\\To prepare paper 2 \\InAlGaN-AlN-GaN HEMT\\Machine Leaning Data\\lstmmodel.hdf5"
checkpointer = ModelCheckpoint( monitor='val_loss',filepath=filepath, verbose=1, save_best_only=True)
history=model.fit(x_traindim, y_traindim, validation_data=(x_testdim, y_testdim), epochs=100, batch_size=16, callbacks=[checkpointer])


In [ ]:
model.save("E:\\Simulations\\Silvaco\\2D HEMT\\EDL\\DATA for modeling\\fom23.37mse.h5")

In [ ]:
result= model.evaluate(x_testdim, y_testdim)

In [ ]:
print(result)

In [ ]:

for i in range(len(X_test)):
    print(r[i]*1000,y_test[i]*1000)

In [ ]:
import numpy as nd
xdim=np.expand_dims((X[42:83]), axis=1)
xdim.shape

In [ ]:
pred_id=model.predict(xdim)
pred_id

In [ ]:
for i in range(len(pred_id)):
    print(pred_id[i][0]*1000, y[42:83][i]*1000)

In [ ]:
X[0:41][2][0]

In [ ]:
a=[]
b=[]
c=[]
for i in range(len(pred_id)):
    a.append(pred_id[i][0])
    b.append(y[42:83][i])
    c.append(X[42:83][i][0])


In [ ]:
c

In [ ]:
import pandas as pd
q={'vd':c, 'pred_id':a, 'id':b }
df=pd.DataFrame(q)
df.to_csv('modelfile1.csv')

In [ ]:
pred_id=model.predict(x_testdim)
pred_id

In [ ]:
for i in range(len(pred_id)):
    print(pred_id[i][0]*1000 - y_testdim[i][0]*1000)